config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :users do
      member do
        get :avalara_information
        put :avalara_information
      end
    end
    resource :avatax_settings do
      get :ping_my_service, :download_avatax_log, :erase_data
    end
    resources :avalara_entity_use_codes do

    end
  end
end

app/views/spree/admin/users/avalara_information.html.erb
<% content_for :page_title do %>
<%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render partial: 'spree/admin/users/sidebar', locals: { current: :account } %>
<%= render partial: 'spree/admin/users/user_page_actions' %>

<fieldset data-hook="admin_user_edit_general_settings" class="alpha twelve columns">
  <legend><%= Spree.t(:general_settings) %></legend>

  <div data-hook="admin_user_edit_form_header">
    <%= render partial: 'spree/shared/error_messages', locals: { target: @user } %>
  </div>

  <div data-hook="admin_user_edit_form">
    <%= form_for [:admin, @user], as: :user, url: avalara_information_admin_user_url(@user), method: :put do |f| %>
    <div class="alpha six columns">
      <div class="field">
        <label>Customer Code</label>
        <input type="text" class="fullwidth" placeholder="<%= @user.id %>", readonly>
      </div>
    </div>
    <% use_codes_list = Spree::AvalaraEntityUseCode.all.map {|use_code| ["#{use_code.use_code}) #{use_code.use_code_description}", use_code.id]} %>
    <div class="omega six columns">
      <%= f.field_container :avalara_entity_use_code_id do %>
        <%= label_tag :avalara_entity_use_code_id, t(:avalara_entity_use_code) %><br />
        <%= f.select(:avalara_entity_use_code_id, use_codes_list, { include_blank: true } ) %>
      <% end %>
    </div>
    <div class="clear"></div>
    <div class="alpha six columns">
      <%= f.field_container :exemption_number do %>
        <%= f.label :exemption_number, Spree.t(:exemption_number) %>
        <%= f.text_field :exemption_number, :class => 'fullwidth' %>
      <% end %>
    </div>
    <div class="omega six columns">
      <%= f.field_container :vat_id do %>
        <%= f.label :vat_id, Spree.t(:vat_identification_number) %>
        <%= f.text_field :vat_id, :class => 'fullwidth' %>
      <% end %>
    </div>
    <br><br><br>
    <div class="clear"></div>
    <% if can?(:update, @user) %>
      <div data-hook="admin_user_edit_form_button">
        <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_users_url } %>
        </div>
    <% end %>
  </div>
  <% end %>
</fieldset>